### ISSUE TITLE
Objectstore connector embedded into Maven project problem

### ISSUE THREAD

**Issue by yurykuchmel** [mulesoft/mule-module-objectstore#11]
Maven WAR project using embedded ObjectStore connector cannot be built due to absence of interface `org.mule.api.process.ProcessAdapter`. Here is dependency declaration:

    <dependency>
       <groupId>org.mule.modules</groupId>
       <artifactId>mule-module-objectstore</artifactId>
       <version>1.2.2</version>
    </dependency>

That dependency cannot work with:

     <dependency>
       <groupId>org.mule.tools.devkit</groupId>
       <artifactId>mule-devkit-annotations</artifactId>
       <version>3.4.0</version>
    </dependency>

but ObjectStore can be compiled with:

     <dependency>
       <groupId>org.mule.tools.devkit</groupId>
       <artifactId>mule-devkit-annotations</artifactId>
       <version>3.3.1</version>
    </dependency>

I think it is not good if there is no backward compatibility between `mule-devkit-annotations` and if I cannot use the latest dependencies in the project.

Please check that.

**Comment by tejaswip** [comment]
The issue could not be replicated and the moving to the lastest version of devkit might have resolved this issue.
