### ISSUE TITLE
`allKeys()` is not consistent with the other methods

### ISSUE THREAD

**Issue by ddossot** [mulesoft/mule-module-objectstore#9]
`allKeys()` returns a `List<Serializable>` while the other methods accept only `String` for keys: allow `Serializable` for other methods too for consistency reasons.

**Comment by tejaswip** [comment]
Refactoring the allKey() operation from List<Serializable> to List<String>, this is contrary to ticket description here however this ensures consistency of key being only String and this will not break compatibility.
